---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: data-service-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: data-service
  {{ end }}
spec:
  selector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      name: data-service-{{ .DRONE_SOURCE_BRANCH }}
      service: data-service-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      name: data-service
      service: data-service
      {{ end }}
  template:
    metadata:
      labels:
        {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        name: data-service-{{ .DRONE_SOURCE_BRANCH }}
        service: data-service-{{ .DRONE_SOURCE_BRANCH }}
        {{ else }}
        name: data-service
        service: data-service
        {{ end }}
        build: "{{.DRONE_BUILD_NUMBER}}"
        commit: "{{.DRONE_COMMIT_SHA}}"
    spec:
      containers:
        - name: data-service
          # release v2.0.1
          image: quay.io/ukhomeofficedigital/hof-rds-api:ee9ea8ca6881fa8e50b1e8945a3f4d13bb355c5e
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
                name: configmap-{{ .DRONE_SOURCE_BRANCH }}
                {{ else }}
                name: configmap
                {{ end }}
          env:
            - name: SERVICE_NAME
              value: "ima"
            - name: LATEST_MIGRATION
              # value: TO BE UPDATED WITH LATEST MIGRATION
            - name: MAX_PAYLOAD_SIZE
              value: "30mb"
            - name: REQUEST_TIMEOUT
              value: "10000"
            - name: HTTPS_PORT
              value: "3443"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: endpoint
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: ima-notprod-rds
                  {{ else }}
                  name: ima-prod
                  {{ end }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db_name
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: ima-notprod-rds
                  {{ else }}
                  name: ima-prod
                  {{ end }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: ima-notprod-rds
                  {{ else }}
                  name: ima-prod
                  {{ end }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: ima-notprod-rds
                  {{ else }}
                  name: ima-prod
                  {{ end }}
          resources:
            requests:
              memory: 4Gi
              cpu: 200m
            limits:
              memory: 8Gi
              cpu: 400m
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /certs
              name: certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
            secretName: branch-tls-external
            {{ else }}
            secretName: data-service-cert-cmio
            {{ end }}
